// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_service.proto

package migrationpb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetStateRequest_State int32

const (
	SetStateRequest_RUNNING SetStateRequest_State = 0
	SetStateRequest_STOPPED SetStateRequest_State = 1
)

var SetStateRequest_State_name = map[int32]string{
	0: "RUNNING",
	1: "STOPPED",
}

var SetStateRequest_State_value = map[string]int32{
	"RUNNING": 0,
	"STOPPED": 1,
}

func (x SetStateRequest_State) String() string {
	return proto.EnumName(SetStateRequest_State_name, int32(x))
}

func (SetStateRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1, 0}
}

type VoidResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidResponse) Reset()         { *m = VoidResponse{} }
func (m *VoidResponse) String() string { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()    {}
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{0}
}

func (m *VoidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidResponse.Unmarshal(m, b)
}
func (m *VoidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidResponse.Marshal(b, m, deterministic)
}
func (m *VoidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidResponse.Merge(m, src)
}
func (m *VoidResponse) XXX_Size() int {
	return xxx_messageInfo_VoidResponse.Size(m)
}
func (m *VoidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidResponse proto.InternalMessageInfo

type SetStateRequest struct {
	State                SetStateRequest_State `protobuf:"varint,1,opt,name=state,proto3,enum=kin.agora.migration.SetStateRequest_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SetStateRequest) Reset()         { *m = SetStateRequest{} }
func (m *SetStateRequest) String() string { return proto.CompactTextString(m) }
func (*SetStateRequest) ProtoMessage()    {}
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1}
}

func (m *SetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStateRequest.Unmarshal(m, b)
}
func (m *SetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStateRequest.Marshal(b, m, deterministic)
}
func (m *SetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStateRequest.Merge(m, src)
}
func (m *SetStateRequest) XXX_Size() int {
	return xxx_messageInfo_SetStateRequest.Size(m)
}
func (m *SetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetStateRequest proto.InternalMessageInfo

func (m *SetStateRequest) GetState() SetStateRequest_State {
	if m != nil {
		return m.State
	}
	return SetStateRequest_RUNNING
}

type SetRateLimitRequest struct {
	Rate                 uint32   `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRateLimitRequest) Reset()         { *m = SetRateLimitRequest{} }
func (m *SetRateLimitRequest) String() string { return proto.CompactTextString(m) }
func (*SetRateLimitRequest) ProtoMessage()    {}
func (*SetRateLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{2}
}

func (m *SetRateLimitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRateLimitRequest.Unmarshal(m, b)
}
func (m *SetRateLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRateLimitRequest.Marshal(b, m, deterministic)
}
func (m *SetRateLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRateLimitRequest.Merge(m, src)
}
func (m *SetRateLimitRequest) XXX_Size() int {
	return xxx_messageInfo_SetRateLimitRequest.Size(m)
}
func (m *SetRateLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRateLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRateLimitRequest proto.InternalMessageInfo

func (m *SetRateLimitRequest) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type QueueRequest struct {
	Items                []*QueueRequest_QueueItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *QueueRequest) Reset()         { *m = QueueRequest{} }
func (m *QueueRequest) String() string { return proto.CompactTextString(m) }
func (*QueueRequest) ProtoMessage()    {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{3}
}

func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest.Unmarshal(m, b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
}
func (m *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(m, src)
}
func (m *QueueRequest) XXX_Size() int {
	return xxx_messageInfo_QueueRequest.Size(m)
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

func (m *QueueRequest) GetItems() []*QueueRequest_QueueItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type QueueRequest_QueueItem struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IgnoreZeroBalance    bool     `protobuf:"varint,2,opt,name=ignore_zero_balance,json=ignoreZeroBalance,proto3" json:"ignore_zero_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueRequest_QueueItem) Reset()         { *m = QueueRequest_QueueItem{} }
func (m *QueueRequest_QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueRequest_QueueItem) ProtoMessage()    {}
func (*QueueRequest_QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{3, 0}
}

func (m *QueueRequest_QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest_QueueItem.Unmarshal(m, b)
}
func (m *QueueRequest_QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest_QueueItem.Marshal(b, m, deterministic)
}
func (m *QueueRequest_QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest_QueueItem.Merge(m, src)
}
func (m *QueueRequest_QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueRequest_QueueItem.Size(m)
}
func (m *QueueRequest_QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest_QueueItem proto.InternalMessageInfo

func (m *QueueRequest_QueueItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *QueueRequest_QueueItem) GetIgnoreZeroBalance() bool {
	if m != nil {
		return m.IgnoreZeroBalance
	}
	return false
}

func init() {
	proto.RegisterEnum("kin.agora.migration.SetStateRequest_State", SetStateRequest_State_name, SetStateRequest_State_value)
	proto.RegisterType((*VoidResponse)(nil), "kin.agora.migration.VoidResponse")
	proto.RegisterType((*SetStateRequest)(nil), "kin.agora.migration.SetStateRequest")
	proto.RegisterType((*SetRateLimitRequest)(nil), "kin.agora.migration.SetRateLimitRequest")
	proto.RegisterType((*QueueRequest)(nil), "kin.agora.migration.QueueRequest")
	proto.RegisterType((*QueueRequest_QueueItem)(nil), "kin.agora.migration.QueueRequest.QueueItem")
}

func init() { proto.RegisterFile("admin_service.proto", fileDescriptor_f9bc00259dc38d22) }

var fileDescriptor_f9bc00259dc38d22 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x0a, 0x5f, 0x15, 0x87, 0x82, 0xb8, 0x3d, 0x48, 0x38, 0x41, 0xe3, 0xa1, 0x6a, 0xb2,
	0x26, 0xf8, 0x07, 0x84, 0x68, 0x0c, 0x89, 0x20, 0x6e, 0xd5, 0x03, 0x1e, 0xc8, 0x02, 0x13, 0xb2,
	0x81, 0x76, 0x71, 0xbb, 0x90, 0xe8, 0x2f, 0xf0, 0x67, 0xf8, 0x53, 0x4d, 0xbb, 0x29, 0x21, 0x04,
	0x23, 0xb7, 0x79, 0x3b, 0xf3, 0xde, 0x9b, 0xbc, 0x59, 0x70, 0xf9, 0x24, 0x14, 0xd1, 0x30, 0x46,
	0xb5, 0x12, 0x63, 0xa4, 0x0b, 0x25, 0xb5, 0x24, 0xee, 0x4c, 0x44, 0x94, 0x4f, 0xa5, 0xe2, 0x34,
	0x14, 0x53, 0xc5, 0xb5, 0x90, 0x51, 0xed, 0x74, 0xc5, 0xe7, 0x62, 0xc2, 0x35, 0x5e, 0x65, 0x85,
	0x99, 0xf6, 0xca, 0xe0, 0xbc, 0x4a, 0x31, 0x61, 0x18, 0x2f, 0x64, 0x14, 0xa3, 0xb7, 0x82, 0xe3,
	0x00, 0x75, 0xa0, 0xb9, 0x46, 0x86, 0xef, 0x4b, 0x8c, 0x35, 0xb9, 0x01, 0x3b, 0x4e, 0x70, 0xd5,
	0xaa, 0x5b, 0x7e, 0xb9, 0x79, 0x41, 0x77, 0x18, 0xd0, 0x2d, 0x12, 0x35, 0xc0, 0x10, 0xbd, 0x06,
	0xd8, 0x29, 0x26, 0x45, 0x38, 0x64, 0x2f, 0xbd, 0x5e, 0xa7, 0x77, 0x5f, 0xf9, 0x97, 0x80, 0xe0,
	0xf9, 0xb1, 0xdf, 0xbf, 0xbb, 0xad, 0x58, 0xde, 0x39, 0xb8, 0x01, 0x6a, 0xc6, 0x35, 0x3e, 0x88,
	0x50, 0xe8, 0xcc, 0x9b, 0xc0, 0x7f, 0x95, 0x59, 0x97, 0x58, 0x5a, 0x7b, 0xdf, 0x16, 0x38, 0x4f,
	0x4b, 0x5c, 0xae, 0x17, 0x6c, 0x81, 0x2d, 0x34, 0x86, 0x71, 0xd5, 0xaa, 0xe7, 0xfd, 0x62, 0xf3,
	0x72, 0xe7, 0x82, 0x9b, 0x0c, 0x03, 0x3a, 0x1a, 0x43, 0x66, 0x98, 0xb5, 0x2e, 0x1c, 0xad, 0xdf,
	0x48, 0x05, 0xf2, 0x33, 0xfc, 0x48, 0x3d, 0x1d, 0x96, 0x94, 0x84, 0x82, 0x2b, 0xa6, 0x91, 0x54,
	0x38, 0xfc, 0x44, 0x25, 0x87, 0x23, 0x3e, 0xe7, 0xd1, 0x18, 0xab, 0xb9, 0xba, 0xe5, 0x17, 0xd8,
	0x89, 0x69, 0x0d, 0x50, 0xc9, 0xb6, 0x69, 0x34, 0xbf, 0x72, 0x60, 0xb7, 0x92, 0xdb, 0x90, 0x00,
	0x0a, 0x59, 0x34, 0xe4, 0x6c, 0x9f, 0xe4, 0x6a, 0x8d, 0x9d, 0x53, 0x9b, 0x47, 0x22, 0x6f, 0xe0,
	0x6c, 0x86, 0x45, 0xfc, 0xdf, 0x84, 0xb7, 0xf3, 0xdc, 0x47, 0xbc, 0x0b, 0x76, 0x1a, 0x05, 0x69,
	0xfc, 0x99, 0xe3, 0x1e, 0x72, 0xed, 0xd2, 0xa0, 0xb8, 0xee, 0x2c, 0x46, 0xa3, 0x83, 0xf4, 0xdb,
	0x5d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0x84, 0x41, 0x52, 0xbb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*VoidResponse, error)
	SetRateLimit(ctx context.Context, in *SetRateLimitRequest, opts ...grpc.CallOption) (*VoidResponse, error)
	Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*VoidResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*VoidResponse, error) {
	out := new(VoidResponse)
	err := c.cc.Invoke(ctx, "/kin.agora.migration.Admin/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SetRateLimit(ctx context.Context, in *SetRateLimitRequest, opts ...grpc.CallOption) (*VoidResponse, error) {
	out := new(VoidResponse)
	err := c.cc.Invoke(ctx, "/kin.agora.migration.Admin/SetRateLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*VoidResponse, error) {
	out := new(VoidResponse)
	err := c.cc.Invoke(ctx, "/kin.agora.migration.Admin/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	SetState(context.Context, *SetStateRequest) (*VoidResponse, error)
	SetRateLimit(context.Context, *SetRateLimitRequest) (*VoidResponse, error)
	Queue(context.Context, *QueueRequest) (*VoidResponse, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) SetState(ctx context.Context, req *SetStateRequest) (*VoidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}
func (*UnimplementedAdminServer) SetRateLimit(ctx context.Context, req *SetRateLimitRequest) (*VoidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRateLimit not implemented")
}
func (*UnimplementedAdminServer) Queue(ctx context.Context, req *QueueRequest) (*VoidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Queue not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.agora.migration.Admin/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SetRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SetRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.agora.migration.Admin/SetRateLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SetRateLimit(ctx, req.(*SetRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kin.agora.migration.Admin/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Queue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kin.agora.migration.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetState",
			Handler:    _Admin_SetState_Handler,
		},
		{
			MethodName: "SetRateLimit",
			Handler:    _Admin_SetRateLimit_Handler,
		},
		{
			MethodName: "Queue",
			Handler:    _Admin_Queue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}
