// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: model.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _model_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Entry with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Entry) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Version

	switch m.Kind.(type) {

	case *Entry_Stellar:

		if v, ok := interface{}(m.GetStellar()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EntryValidationError{
					field:  "Stellar",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// EntryValidationError is the validation error returned by Entry.Validate if
// the designated constraints aren't met.
type EntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EntryValidationError) ErrorName() string { return "EntryValidationError" }

// Error satisfies the builtin error interface
func (e EntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EntryValidationError{}

// Validate checks the field values on StellarEntry with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *StellarEntry) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Ledger

	// no validation rules for PagingToken

	if m.GetLedgerCloseTime() == nil {
		return StellarEntryValidationError{
			field:  "LedgerCloseTime",
			reason: "value is required",
		}
	}

	if l := len(m.GetEnvelopeXdr()); l < 1 || l > 10240 {
		return StellarEntryValidationError{
			field:  "EnvelopeXdr",
			reason: "value length must be between 1 and 10240 bytes, inclusive",
		}
	}

	if l := len(m.GetResultXdr()); l < 1 || l > 10240 {
		return StellarEntryValidationError{
			field:  "ResultXdr",
			reason: "value length must be between 1 and 10240 bytes, inclusive",
		}
	}

	return nil
}

// StellarEntryValidationError is the validation error returned by
// StellarEntry.Validate if the designated constraints aren't met.
type StellarEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StellarEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StellarEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StellarEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StellarEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StellarEntryValidationError) ErrorName() string { return "StellarEntryValidationError" }

// Error satisfies the builtin error interface
func (e StellarEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStellarEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StellarEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StellarEntryValidationError{}
