// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KinVersion int32

const (
	KinVersion_UNKNOWN  KinVersion = 0
	KinVersion_RESERVED KinVersion = 1
	KinVersion_KIN2     KinVersion = 2
	KinVersion_KIN3     KinVersion = 3
)

var KinVersion_name = map[int32]string{
	0: "UNKNOWN",
	1: "RESERVED",
	2: "KIN2",
	3: "KIN3",
}

var KinVersion_value = map[string]int32{
	"UNKNOWN":  0,
	"RESERVED": 1,
	"KIN2":     2,
	"KIN3":     3,
}

func (x KinVersion) String() string {
	return proto.EnumName(KinVersion_name, int32(x))
}

func (KinVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

// Entry is a generalized history entry that contains a blockchain
// transaction, as well as the KinVersion the transaction is for.
//
// This allows for the generalization of a history store, which allows
// for a contiguous view of history accross blockchains.
type Entry struct {
	Version KinVersion `protobuf:"varint,1,opt,name=version,proto3,enum=KinVersion" json:"version,omitempty"`
	// Types that are valid to be assigned to Kind:
	//	*Entry_Stellar
	Kind                 isEntry_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetVersion() KinVersion {
	if m != nil {
		return m.Version
	}
	return KinVersion_UNKNOWN
}

type isEntry_Kind interface {
	isEntry_Kind()
}

type Entry_Stellar struct {
	Stellar *StellarEntry `protobuf:"bytes,2,opt,name=stellar,proto3,oneof"`
}

func (*Entry_Stellar) isEntry_Kind() {}

func (m *Entry) GetKind() isEntry_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Entry) GetStellar() *StellarEntry {
	if x, ok := m.GetKind().(*Entry_Stellar); ok {
		return x.Stellar
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entry_Stellar)(nil),
	}
}

type StellarEntry struct {
	Ledger               uint64               `protobuf:"varint,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	PagingToken          uint64               `protobuf:"varint,2,opt,name=paging_token,json=pagingToken,proto3" json:"paging_token,omitempty"`
	LedgerCloseTime      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ledger_close_time,json=ledgerCloseTime,proto3" json:"ledger_close_time,omitempty"`
	EnvelopeXdr          []byte               `protobuf:"bytes,4,opt,name=envelope_xdr,json=envelopeXdr,proto3" json:"envelope_xdr,omitempty"`
	ResultXdr            []byte               `protobuf:"bytes,5,opt,name=result_xdr,json=resultXdr,proto3" json:"result_xdr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StellarEntry) Reset()         { *m = StellarEntry{} }
func (m *StellarEntry) String() string { return proto.CompactTextString(m) }
func (*StellarEntry) ProtoMessage()    {}
func (*StellarEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *StellarEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StellarEntry.Unmarshal(m, b)
}
func (m *StellarEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StellarEntry.Marshal(b, m, deterministic)
}
func (m *StellarEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StellarEntry.Merge(m, src)
}
func (m *StellarEntry) XXX_Size() int {
	return xxx_messageInfo_StellarEntry.Size(m)
}
func (m *StellarEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StellarEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StellarEntry proto.InternalMessageInfo

func (m *StellarEntry) GetLedger() uint64 {
	if m != nil {
		return m.Ledger
	}
	return 0
}

func (m *StellarEntry) GetPagingToken() uint64 {
	if m != nil {
		return m.PagingToken
	}
	return 0
}

func (m *StellarEntry) GetLedgerCloseTime() *timestamp.Timestamp {
	if m != nil {
		return m.LedgerCloseTime
	}
	return nil
}

func (m *StellarEntry) GetEnvelopeXdr() []byte {
	if m != nil {
		return m.EnvelopeXdr
	}
	return nil
}

func (m *StellarEntry) GetResultXdr() []byte {
	if m != nil {
		return m.ResultXdr
	}
	return nil
}

func init() {
	proto.RegisterEnum("KinVersion", KinVersion_name, KinVersion_value)
	proto.RegisterType((*Entry)(nil), "Entry")
	proto.RegisterType((*StellarEntry)(nil), "StellarEntry")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x6f, 0xa2, 0x40,
	0x14, 0xc6, 0x1d, 0x05, 0x61, 0x1f, 0xec, 0x2e, 0x3b, 0x87, 0x5d, 0xe2, 0x65, 0x5d, 0x93, 0x4d,
	0x74, 0x93, 0xc5, 0x44, 0x8f, 0xbd, 0xd1, 0x92, 0xb4, 0x31, 0xa1, 0x66, 0xb4, 0xd6, 0x1b, 0xc1,
	0x32, 0x25, 0xc4, 0x91, 0x21, 0xc3, 0x68, 0xda, 0x9e, 0xfa, 0x37, 0xf5, 0x7f, 0xeb, 0xc5, 0x53,
	0x03, 0x23, 0x69, 0x93, 0xde, 0xde, 0xf7, 0xfd, 0xbe, 0xc7, 0xe3, 0x1b, 0xb0, 0x76, 0x3c, 0xa1,
	0xcc, 0x2b, 0x04, 0x97, 0xbc, 0xf7, 0xeb, 0x10, 0xb3, 0x2c, 0x89, 0x25, 0x1d, 0x37, 0xc3, 0x09,
	0xfc, 0x4e, 0x39, 0x4f, 0x19, 0x1d, 0xd7, 0x6a, 0xb3, 0xbf, 0x1f, 0xcb, 0x6c, 0x47, 0x4b, 0x19,
	0xef, 0x0a, 0x15, 0x18, 0xc4, 0xa0, 0x07, 0xb9, 0x14, 0x8f, 0xf8, 0x2f, 0x18, 0x07, 0x2a, 0xca,
	0x8c, 0xe7, 0x2e, 0xea, 0xa3, 0xe1, 0xb7, 0x89, 0xe5, 0xcd, 0xb2, 0x7c, 0xa5, 0x2c, 0xd2, 0x30,
	0x3c, 0x02, 0xa3, 0x94, 0x94, 0xb1, 0x58, 0xb8, 0xed, 0x3e, 0x1a, 0x5a, 0x93, 0xaf, 0xde, 0x42,
	0xe9, 0xfa, 0x33, 0x97, 0x2d, 0xd2, 0x70, 0xbf, 0x0b, 0xda, 0x36, 0xcb, 0x93, 0xc1, 0x2b, 0x02,
	0xfb, 0x63, 0x06, 0xff, 0x84, 0x2e, 0xa3, 0x49, 0x4a, 0x45, 0x7d, 0x49, 0x23, 0x27, 0x85, 0xff,
	0x80, 0x5d, 0xc4, 0x69, 0x96, 0xa7, 0x91, 0xe4, 0x5b, 0x9a, 0xd7, 0x07, 0x34, 0x62, 0x29, 0x6f,
	0x59, 0x59, 0x78, 0x0e, 0x3f, 0x54, 0x38, 0xba, 0x63, 0xbc, 0xa4, 0x51, 0x55, 0xc7, 0xed, 0xd4,
	0x3f, 0xd2, 0xf3, 0x54, 0x57, 0xaf, 0xe9, 0xea, 0x2d, 0x9b, 0xae, 0xbe, 0x79, 0xf4, 0xf5, 0x17,
	0xd4, 0x36, 0x11, 0xf9, 0xae, 0xd6, 0xcf, 0xab, 0xed, 0x8a, 0xe3, 0xff, 0x60, 0xd3, 0xfc, 0x40,
	0x19, 0x2f, 0x68, 0xf4, 0x90, 0x08, 0x57, 0xeb, 0xa3, 0xa1, 0xed, 0xc3, 0xd1, 0x37, 0x9e, 0x74,
	0x07, 0xb9, 0xcf, 0x73, 0x62, 0x35, 0x7c, 0x9d, 0x08, 0x3c, 0x02, 0x10, 0xb4, 0xdc, 0x33, 0x59,
	0x87, 0xf5, 0x4f, 0xe1, 0x2f, 0x8a, 0xae, 0x13, 0xf1, 0xef, 0x0c, 0xe0, 0xfd, 0x05, 0xb1, 0x05,
	0xc6, 0x4d, 0x38, 0x0b, 0xaf, 0x6f, 0x43, 0xa7, 0x85, 0x6d, 0x30, 0x49, 0xb0, 0x08, 0xc8, 0x2a,
	0xb8, 0x70, 0x10, 0x36, 0x41, 0x9b, 0x5d, 0x85, 0x13, 0xa7, 0x7d, 0x9a, 0xa6, 0x4e, 0x67, 0xd3,
	0xad, 0x5b, 0x4c, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x02, 0x97, 0x8f, 0xbc, 0xe7, 0x01, 0x00,
	0x00,
}
