// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventspb.proto

package eventspb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	SubmissionTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=submission_time,json=submissionTime,proto3" json:"submission_time,omitempty"`
	// Types that are valid to be assigned to Kind:
	//	*Event_TransactionEvent
	//	*Event_SimulationEvent
	Kind                 isEvent_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58f44a09bfc228d, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSubmissionTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmissionTime
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_TransactionEvent struct {
	TransactionEvent *TransactionEvent `protobuf:"bytes,2,opt,name=transaction_event,json=transactionEvent,proto3,oneof"`
}

type Event_SimulationEvent struct {
	SimulationEvent *SimulationEvent `protobuf:"bytes,3,opt,name=simulation_event,json=simulationEvent,proto3,oneof"`
}

func (*Event_TransactionEvent) isEvent_Kind() {}

func (*Event_SimulationEvent) isEvent_Kind() {}

func (m *Event) GetKind() isEvent_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Event) GetTransactionEvent() *TransactionEvent {
	if x, ok := m.GetKind().(*Event_TransactionEvent); ok {
		return x.TransactionEvent
	}
	return nil
}

func (m *Event) GetSimulationEvent() *SimulationEvent {
	if x, ok := m.GetKind().(*Event_SimulationEvent); ok {
		return x.SimulationEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_TransactionEvent)(nil),
		(*Event_SimulationEvent)(nil),
	}
}

type TransactionEvent struct {
	// Maximum size taken from: https://github.com/solana-labs/solana/blob/39b3ac6a8d29e14faa1de73d8b46d390ad41797b/sdk/src/packet.rs#L9-L13
	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// The proto serialized transaction error from commonpb.TransactionError
	TransactionError     []byte   `protobuf:"bytes,2,opt,name=transaction_error,json=transactionError,proto3" json:"transaction_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58f44a09bfc228d, []int{1}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetTransaction() []byte {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TransactionEvent) GetTransactionError() []byte {
	if m != nil {
		return m.TransactionError
	}
	return nil
}

type SimulationEvent struct {
	// Maximum size taken from: https://github.com/solana-labs/solana/blob/39b3ac6a8d29e14faa1de73d8b46d390ad41797b/sdk/src/packet.rs#L9-L13
	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// The proto serialized transaction error from commonpb.TransactionError
	TransactionError     []byte   `protobuf:"bytes,2,opt,name=transaction_error,json=transactionError,proto3" json:"transaction_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulationEvent) Reset()         { *m = SimulationEvent{} }
func (m *SimulationEvent) String() string { return proto.CompactTextString(m) }
func (*SimulationEvent) ProtoMessage()    {}
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c58f44a09bfc228d, []int{2}
}

func (m *SimulationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulationEvent.Unmarshal(m, b)
}
func (m *SimulationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulationEvent.Marshal(b, m, deterministic)
}
func (m *SimulationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulationEvent.Merge(m, src)
}
func (m *SimulationEvent) XXX_Size() int {
	return xxx_messageInfo_SimulationEvent.Size(m)
}
func (m *SimulationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SimulationEvent proto.InternalMessageInfo

func (m *SimulationEvent) GetTransaction() []byte {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SimulationEvent) GetTransactionError() []byte {
	if m != nil {
		return m.TransactionError
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*TransactionEvent)(nil), "TransactionEvent")
	proto.RegisterType((*SimulationEvent)(nil), "SimulationEvent")
}

func init() { proto.RegisterFile("eventspb.proto", fileDescriptor_c58f44a09bfc228d) }

var fileDescriptor_c58f44a09bfc228d = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0x2e, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12, 0x2f, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x87, 0x31, 0xa0, 0x12, 0xf2, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9,
	0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x49, 0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x01,
	0x44, 0x81, 0xd2, 0x7d, 0x46, 0x2e, 0x56, 0x57, 0x90, 0x61, 0x42, 0xbe, 0x5c, 0xfc, 0xc5, 0xa5,
	0x49, 0xb9, 0x99, 0xc5, 0xc5, 0x99, 0xf9, 0x79, 0xf1, 0x20, 0x75, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xdc, 0x46, 0x52, 0x7a, 0x10, 0x43, 0xf4, 0x60, 0x86, 0xe8, 0x85, 0xc0, 0x0c, 0x71, 0xe2, 0xf8,
	0xe5, 0xc4, 0xba, 0x89, 0x91, 0x89, 0x83, 0x31, 0x88, 0x0f, 0xa1, 0x19, 0x24, 0x2d, 0xe4, 0xc0,
	0x25, 0x58, 0x52, 0x94, 0x98, 0x57, 0x9c, 0x98, 0x5c, 0x02, 0x32, 0x0f, 0xec, 0x60, 0x09, 0x26,
	0xb0, 0x81, 0x82, 0x7a, 0x21, 0x08, 0x19, 0xb0, 0xe5, 0x1e, 0x0c, 0x41, 0x02, 0x25, 0x68, 0x62,
	0x42, 0xb6, 0x5c, 0x02, 0xc5, 0x99, 0xb9, 0xa5, 0x39, 0x89, 0x48, 0x06, 0x30, 0x83, 0x0d, 0x10,
	0xd0, 0x0b, 0x86, 0x4b, 0xc0, 0xf4, 0xf3, 0x17, 0xa3, 0x0a, 0x39, 0xb1, 0x71, 0xb1, 0x64, 0x67,
	0xe6, 0xa5, 0x28, 0x95, 0x73, 0x09, 0xa0, 0x5b, 0x27, 0xa4, 0xc3, 0xc5, 0x8d, 0x64, 0x1d, 0xd8,
	0x9f, 0x3c, 0x4e, 0x5c, 0xbf, 0x9c, 0xd8, 0xab, 0x58, 0x05, 0x18, 0x25, 0x2e, 0x70, 0x06, 0x21,
	0x4b, 0x0b, 0x99, 0xa2, 0x79, 0xa5, 0xa8, 0x28, 0xbf, 0x08, 0xec, 0x15, 0x1e, 0xb0, 0xff, 0xab,
	0x98, 0x25, 0x1a, 0x02, 0x50, 0xdd, 0x0f, 0x52, 0xa1, 0x54, 0xc6, 0xc5, 0x8f, 0xe6, 0x4c, 0xba,
	0xd8, 0xeb, 0xc4, 0x15, 0xc5, 0x01, 0x4b, 0x1e, 0x49, 0x6c, 0xe0, 0x38, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0xbb, 0xc4, 0xd5, 0x31, 0x02, 0x00, 0x00,
}
